const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const{chromium}=require('C:/Users/La_pa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// TEST: reproduce the marketplace navigation with its actual production styles and unequal descriptions.
(async()=>{const root=process.env.RELEASE_ROOT,web=path.join(root,'web'),index=fs.readFileSync(path.join(web,'index.html'),'utf8');const links=[...index.matchAll(/<link\b[^>]*>/g)].map(m=>m[0]).filter(s=>/stylesheet/.test(s)&&!s.includes('fbs-equal-tiles-20260929.css')).join('');
const labels=['Активные заказы по FBS','Отгруженные','Отменённые заказы','Стоимость обработки FBS','Калькулятор стоимости','Архив','Назначение стоимости обработки'];const descriptions=['Новые заказы, сборка, упаковка и готовность к передаче.','Переданные заказы со статусами, автоматически получаемыми из API.','Заказы, отменённые продавцом, покупателем или перевозчиком.','Отгруженные заказы, тарифы, начисления и выставленные счета.','Предварительный расчёт обработки и доставки партии FBS.','Завершённые заказы, полученные покупателями.','Услуги клиента, доставка, шаг доплаты и комплектация коробов.'];
const markup=labels.map((s,i)=>`<div class="fbs-tile fbs-tile--${['red','green','red','amber','blue','slate','violet'][i]}${i===0?' is-active fbs-tile--has-clients':''}"><button class="fbs-tile__open" role="tab"><span class="fbs-tile__icon">${['▣','▰','×','₽','▦','▤','☷'][i]}</span><span class="fbs-tile__content"><span class="fbs-tile__number">${i+1}</span><strong>${s}</strong><small>${descriptions[i]}</small></span><span class="fbs-tile__count">${i===4?'1–3000':i===6?'тарифы':'…'}</span></button>${i===0?'<div class="fbs-tile__clients"><span class="fbs-tile__clients-title">Клиенты с заказами</span><div id="clients"></div></div>':''}</div>`).join('');
const html=`<!doctype html><html data-ui-theme="modern" data-ui-variant="la_panthera"><head>${links}<link rel="stylesheet" href="/assets/FbsPanel-BjCaow1R.css"><link rel="stylesheet" href="/assets/fbs-DGXLmhG0.css">${process.env.PATCH?'<link rel="stylesheet" href="/assets/fbs-equal-tiles-20260929.css">':''}<style>body{margin:0;padding:20px}.app-layout{display:block!important}.fbs-tiles{width:100%}#clients{display:contents}</style></head><body><div class="app-layout workspace-content" data-ui-theme="modern" data-ui-variant="la_panthera"><div class="fbs-tiles" role="tablist">${markup}</div></div></body></html>`;
const server=http.createServer((req,res)=>{const n=req.url.split('?')[0];if(n==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);return;}const p=path.join(web,n);if(!fs.existsSync(p)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',p.endsWith('.css')?'text/css':'application/octet-stream');res.end(fs.readFileSync(p));});await new Promise(r=>server.listen(0,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage();await p.goto('http://127.0.0.1:'+server.address().port);let checks=0;
for(const variant of ['modern','classic','soul','space','spirit','la_panthera','polar','future3100','obsidian','aerospace','winx'])for(const style of variant==='la_panthera'?['dark','light']:['dark'])for(const width of [2100,1200,390])for(const clients of [0,3]){
await p.setViewportSize({width,height:1000});await p.evaluate(({variant,style,clients})=>{for(const e of [document.documentElement,document.querySelector('.app-layout')]){e.dataset.uiVariant=variant;e.dataset.uiStyle=style;}document.getElementById('clients').innerHTML=clients?Array.from({length:clients},(_,i)=>`<button><span>Клиент ${i+1} с длинным названием</span><strong>2</strong></button>`).join(''):'<span class="fbs-tile__clients-empty">Активных заказов Яндекс Маркет нет</span>';},{variant,style,clients});
const data=await p.locator('.fbs-tile__open').evaluateAll(ns=>ns.map(e=>{const r=e.getBoundingClientRect(),c=e.querySelector('.fbs-tile__count').getBoundingClientRect(),d=e.querySelector('small').getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height,count:c.y,descriptionBottom:d.bottom,countTop:c.top};}));
for(const row of data){const same=data.filter(x=>Math.abs(x.y-row.y)<1);for(const other of same){assert.ok(Math.abs(row.h-other.h)<1,`${variant}/${width}: unequal heights ${row.h}/${other.h}`);assert.ok(Math.abs(row.w-other.w)<1);assert.ok(Math.abs(row.count-other.count)<1,'counters not aligned');}assert.ok(row.descriptionBottom<=row.countTop+1,'description overlaps counter');}
assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page horizontal overflow');const a=await p.locator('.fbs-tile__open').first().boundingBox(),c=await p.locator('.fbs-tile__clients').boundingBox();assert.ok(c.y>=a.y+a.height-1,'client block overlaps tile');checks++;
if(variant==='la_panthera'&&width===2100&&clients===3)await p.locator('.fbs-tiles').screenshot({path:path.join(root,`tiles-${style}.png`)});
}
console.log('PASS actual styles: '+checks+' theme/width/client cases; equal tiles, aligned counters, no overlap.');}finally{await b.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
