const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{createRequire}=require('node:module');
const web=path.resolve(__dirname,'..'),req=createRequire(path.join(web,'package.json')),vite=createRequire(req.resolve('vite/package.json'));
const {chromium}=require('C:/Users/La_pa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
// TEST: real React callbacks, keyboard disclosures, theme independence and recovery permissions.
(async()=>{
const runtime=process.env.RELEASE_ROOT;
let server;
const built=await vite('esbuild').build({stdin:{contents:(runtime?`const {React,createRoot}=window.__main;const ClientRequestsTable=window.__Table;`:`import React from 'react';import{createRoot}from'react-dom/client';import{ClientRequestsTable}from'./src/components/client-requests/ClientRequestsTable';`)+`
window.calls=[];const root=createRoot(document.getElementById('root'));window.render=(fbs=true,admin=true,status='SUBMITTED')=>{const props={modernActions:true,canManageRequestRecovery:admin,canChangeStatus:true,canPickOutbound:true,canCancelRequests:true,canEditAnyRequest:false,canRefreshPickInstruction:true,items:[{id:'r',number:1550,type:'OUTBOUND',status,priority:'NORMAL',title:fbs?'FBS WB · Мой склад Новосибирск — 5 заказа(а/ов)':'ФБО Никольское',client:{id:'c',code:'CL-000001',name:'ИП Лукин Илья Ильич'},clientId:'c',createdAt:'2026-09-29T09:00:00Z',items:[{id:'i',quantity:2}],packages:[],files:[]}]};for(const k of ['onOpenDocument','onDownloadRequestItems','onStatusChange','onCancelRequest','onEditRequest','onOpenOnlineExecution','onOpenFbsOrders','onOpenFbsRoute','onSelectManualBoxes','onOpenFbsBoxSearch','onOpenPickInstruction','onRefreshPickInstruction','onSyncTsd','onCheckSupplyConsistency','onDownloadPickInstruction','onUploadManualInstruction','onEmergencyPackedXlsx','onPickOutbound','onPackageOutbound','onShipOutbound'])props[k]=(r)=>window.calls.push([k,r?.id||r]);if(!admin){delete props.onUploadManualInstruction;delete props.onEmergencyPackedXlsx;delete props.onRollbackEmergencyClose;}root.render(<ClientRequestsTable {...props}/>)};window.render();`,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic'});
const browser=await chromium.launch({channel:'msedge',headless:true});
try{const page=await browser.newPage({viewport:{width:1600,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));if(runtime){
const http=require('node:http'),base=path.join(runtime,'web'),proof=JSON.parse(fs.readFileSync(path.join(runtime,'proof.json')));
server=http.createServer((req,res)=>{const n=req.url==='/'?'index.html':req.url.slice(1).split('?')[0],file=path.join(base,n);if(!fs.existsSync(file)){res.writeHead(404);res.end();return;}res.setHeader('Content-Type',n.endsWith('.js')?'text/javascript':n.endsWith('.css')?'text/css':'text/html');let content=fs.readFileSync(file);if(n==='assets/'+proof.entry)content=Buffer.concat([content,Buffer.from(';window.__main={React:x,createRoot:iT.createRoot};')]);if(n==='assets/'+proof.requests)content=Buffer.concat([content,Buffer.from(';window.__Table=ui;window.__Online=Ui;')]);res.end(content);});await new Promise(r=>server.listen(0,'127.0.0.1',r));
await page.route('**/api/v1/**',r=>r.fulfill({contentType:'application/json',body:'[]'}));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.__main);
await page.evaluate(async n=>{await import('/assets/'+n);const old=document.getElementById('root');old.style.display='none';old.id='app-original';const host=document.createElement('div');host.id='root';host.className='app-layout workspace-content';host.dataset.uiTheme='modern';host.style.display='block';document.body.append(host);},proof.requests);
await page.addStyleTag({url:'/assets/ClientRequestsPanel-DSREBZ1c.css'});
}else{await page.setContent('<html data-ui-theme="modern"><body><div id="root" class="app-layout workspace-content" data-ui-theme="modern" style="display:block"></div></body></html>');
for(const name of ['styles.css','components/client-requests/client-requests.css','components/layout/la-panthera-theme.css','components/layout/la-panthera-light.css','components/client-requests/request-action-menus.css'])await page.addStyleTag({content:fs.readFileSync(path.join(web,'src',name),'utf8')});
}
await page.addScriptTag({content:built.outputFiles[0].text});
await page.addStyleTag({content:'.client-request-table__warehouse-cell { width: 235px !important; max-width:235px !important; }'});
for(const variant of ['modern','classic','soul','space','spirit','la_panthera','polar','future3100','obsidian','aerospace','winx'])for(const style of variant==='la_panthera'?['dark','light']:['dark']){
await page.evaluate(({variant,style})=>{document.documentElement.dataset.uiVariant=variant;document.documentElement.dataset.uiStyle=style;window.render();window.calls=[];document.querySelectorAll('details').forEach(e=>e.open=false);},{variant,style});
// TEST: four equal, centered rows with identical surfaces in every theme.
const topRows=page.locator('.request-action-menu > button, .request-action-menu > details > summary');
const rows=await topRows.evaluateAll(ns=>ns.map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return {x:r.x,y:r.y,w:r.width,h:r.height,bg:s.background,color:s.color,align:s.textAlign,justify:s.justifyContent}}));
assert.equal(rows.length,4);for(const [i,row] of rows.entries()){assert.ok(Math.abs(row.w-rows[0].w)<1,variant+' equal widths');assert.ok(Math.abs(row.h-rows[0].h)<1,variant+' equal heights');assert.equal(row.bg,rows[0].bg,variant+' same surface');assert.equal(row.color,rows[0].color,variant+' same ink');assert.equal(row.align,'center');assert.equal(row.justify,'center');if(i)assert.ok(row.y>=rows[i-1].y+rows[i-1].h,variant+' sequential rows');}
// TEST: long request names remain complete at the actual narrow identity width.
await page.locator('.client-request-title').first().evaluate(e=>{e.style.width='175px'});
assert.ok(await page.locator('.client-request-title').first().evaluate(e=>getComputedStyle(e).maxHeight==='none' && getComputedStyle(e).webkitLineClamp==='none'),variant+' clipped title');
await page.getByRole('button',{name:'Онлайн',exact:true}).click();await page.getByRole('button',{name:'К заказам FBS',exact:true}).click();await page.getByRole('button',{name:'Остатки и короба',exact:true}).click();
for(const name of ['Маршрут','Состав','Источники товара','Инструкция','Редактировать заявку','Отменить заявку'])assert.equal(await page.getByRole('button',{name,exact:true}).count(),0);
const extra=page.locator('.request-action-menu summary').filter({hasText:/^Ещё$/});await extra.focus();await page.keyboard.press('Enter');
for(const name of ['Проверить с WB','Обновить данные WB / ТСД','Пересчитать подбор и маршрут'])await page.getByRole('button',{name,exact:true}).click();
assert.equal(await page.getByText('Администрирование',{exact:true}).count(),0);assert.equal(await page.getByText('Ручные этапы заявки',{exact:true}).count(),0);
await page.locator('.request-action-menu summary').filter({hasText:/^Документы$/}).click();await page.getByRole('button',{name:'Состав XLSX',exact:true}).click();await page.getByRole('button',{name:'Лист подбора PDF',exact:true}).click();
const clipped=await page.locator('.request-action-menu summary, .request-action-menu button').evaluateAll(nodes=>nodes.filter(e=>e.getClientRects().length && e.scrollWidth>e.clientWidth+1).map(e=>e.textContent));assert.deepEqual(clipped,[],variant+' overflowing action labels');
const calls=await page.evaluate(()=>window.calls);assert.equal(calls.length,8);assert.ok(calls.every(c=>c[1]==='r'));assert.equal(new Set(calls.map(c=>c[0])).size,8);
await extra.click();await page.locator('.request-action-menu summary').filter({hasText:/^Документы$/}).click();
}
await page.evaluate(()=>window.render(false,false));await page.getByRole('button',{name:'Обновить план',exact:true}).waitFor();const fboRows=await page.locator('.request-action-menu > button, .request-action-menu > details > summary').evaluateAll(ns=>ns.map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}}));assert.equal(fboRows.length,4);for(const [i,r] of fboRows.entries()){assert.ok(Math.abs(r.w-fboRows[0].w)<1);assert.equal(r.h,56);if(i)assert.ok(r.y>=fboRows[i-1].y+fboRows[i-1].h);}await page.locator('.request-action-menu summary').filter({hasText:/^Ещё$/}).click();assert.equal(await page.getByText('Администрирование',{exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Маршрут',exact:true}).count(),0);
await page.evaluate(()=>window.render(false,false,'DONE'));await page.waitForTimeout(50);assert.equal(await page.getByRole('button',{name:'Обновить план',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Отменить заявку',exact:true}).count(),0);
await page.evaluate(()=>window.render(true,true));await page.waitForTimeout(50);for(const el of await page.locator('details[open]').all())await el.evaluate(e=>e.open=false);
await page.evaluate(()=>{document.documentElement.dataset.uiVariant='la_panthera';document.documentElement.dataset.uiStyle='light'});await page.locator('.request-action-menu summary').filter({hasText:/^Ещё$/}).click();
if(process.env.SCREENSHOT_PATH){await page.locator('#root').evaluate(e=>{e.dataset.uiVariant='la_panthera';e.dataset.uiStyle='light'});await page.locator('.client-request-table-wrap').screenshot({path:process.env.SCREENSHOT_PATH});}
// TEST: actual online modal keeps document callbacks, hides unauthorized actions, and refresh/close stay outside.
if(runtime){
await page.evaluate(()=>{const host=document.createElement('div');host.id='online-test';document.body.append(host);const root=window.__main.createRoot(host);window.onlineCalls=[];window.renderOnline=(allowed=true)=>root.render(window.__main.React.createElement(window.__Online,{request:{id:'r',title:'FBS — 5 заказов',client:{name:'Тест'},items:[],packages:[]},plan:{fbsAssembly:{rows:[],totalOrders:0,completedOrders:0,startedOrders:0}},status:'ready',onEditRequestAction:allowed?()=>window.onlineCalls.push('edit'):undefined,onCancelRequestAction:allowed?()=>window.onlineCalls.push('cancel'):undefined,onDownloadBoxes:()=>window.onlineCalls.push('boxes'),onDownloadContents:()=>window.onlineCalls.push('contents'),onRefresh:()=>window.onlineCalls.push('refresh'),onClose:()=>window.onlineCalls.push('close')}));window.renderOnline();});
const toolbar=page.locator('#online-test .request-online-toolbar');await toolbar.waitFor();
await toolbar.locator('summary').filter({hasText:'Документы'}).click();await toolbar.getByRole('button',{name:'Короба WMS',exact:true}).click();
await toolbar.getByRole('button',{name:'Короба на отправку XLSX',exact:true}).click();await toolbar.getByRole('button',{name:'Содержимое коробов XLSX',exact:true}).click();
await toolbar.locator('summary').filter({hasText:'Действия с заявкой'}).click();await toolbar.getByRole('button',{name:'Редактировать заявку',exact:true}).click();await toolbar.getByRole('button',{name:'Отменить заявку',exact:true}).click();await toolbar.locator('button[title="Обновить онлайн-данные"]').click();await toolbar.locator('button[title="Закрыть"]').click();
assert.deepEqual(await page.evaluate(()=>window.onlineCalls),['boxes','contents','edit','cancel','refresh','close']);
await page.evaluate(()=>window.renderOnline(false));await page.waitForTimeout(30);assert.equal(await toolbar.getByText('Действия с заявкой',{exact:true}).count(),0);
if(process.env.SCREENSHOT_PATH)await page.locator('#online-test .online-execution-modal__header').screenshot({path:process.env.SCREENSHOT_PATH.replace('.png','-online.png')});
}
assert.deepEqual(errors,[]);console.log('PASS: request menus, 8 distinct callbacks, keyboard, themes, FBO/FBS, admin and terminal status restrictions');
}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1});
