// TEST: exercise the exact patched production graph with local read-only API fixtures.
const fs=require('node:fs'),http=require('node:http'),assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const dir=path.resolve(process.argv[2]),proof=JSON.parse(fs.readFileSync(dir+'/proof.json'));
const line={id:'one',kind:'CHARGE',date:'2026-10-01',description:'Обработка FBS',requestNumber:1244,orderIds:['5894299305'],quantity:'2',unitPriceRub:'50',totalRub:100,invoices:[],buckets:['unbilled']};
const report={enabled:true,periodFrom:'2026-10-01',periodTo:'2026-10-02',warehouseName:'Москва',warehouseId:'w1',calculatedAt:'2026-10-02',workCoverage:'FBS_CONFIRMED_OPERATIONS',rows:[{client:{id:'c1',name:'Тестовый клиент',code:'CL1'},warehouseId:'w1',warehouseName:'Москва',unbilledRub:100,draftRub:0,reviewRub:0,debtRub:50,overdueRub:0,clientAdvanceRub:25,missingWorkCount:1,lines:[line]}],issues:[{id:'missing',clientId:'c1',clientName:'Тестовый клиент',code:'WORK_WITHOUT_CHARGE',reason:'Начисление не найдено',action:'Проверить тариф',line:{...line,totalRub:null,kind:'WORK'}}]};
(async()=>{const calls=[],errors=[];const server=http.createServer((req,res)=>{
 res.setHeader('Content-Type','application/json; charset=utf-8');
 if(req.url==='/fixture'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(`<meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/assets/billing-settlements-20261002.css"><div id="root"></div><div id="test"></div><script type="module">import{TestReact as React,TestDom,TestJsx as j}from'/assets/${proof.entry}';import{BillingPanel}from'/assets/${proof.billing}';TestDom.createRoot(document.getElementById('test')).render(j.jsx(BillingPanel,{session:{accessToken:'fixture',user:{id:'fixture',name:'Test',roleCodes:['OWNER'],permissionCodes:['billing:read','billing:write','system:admin'],activeWarehouseId:'w1'}}}));</script>`);}
 if(req.url.startsWith('/api/v1/')){calls.push({method:req.method,url:req.url,auth:req.headers.authorization});if(req.url.includes('/billing/settlements'))return res.end(JSON.stringify(report));if(req.url.startsWith('/api/v1/clients'))return res.end(JSON.stringify([{id:'c1',name:'Тестовый клиент',code:'CL1'}]));return res.end('[]');}
 const name=req.url.split('/assets/')[1]?.split('?')[0];if(!name||!proof.files[name]){res.statusCode=404;return res.end();}
 res.setHeader('Content-Type',name.endsWith('.js')?'application/javascript':'text/css');let s=fs.readFileSync(dir+'/'+name,'utf8');if(name===proof.entry)s+='\nexport{x as TestReact,iT as TestDom,e as TestJsx};';res.end(s);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>{errors.push(e.message);console.error('Browser:',e.stack)});await page.goto('http://127.0.0.1:'+server.address().port+'/fixture');const root=page.locator('#test');await root.getByRole('tab',{name:'Клиенты и расчёты'}).click();await root.getByRole('button',{name:/^Не выставлено:/}).click();const detail=root.getByRole('region',{name:'Расшифровка суммы'});await detail.locator('summary').click();assert.match(await detail.innerText(),/1244/);assert.match(await detail.innerText(),/5894299305/);assert.match(await root.getByRole('region',{name:'Требует проверки'}).innerText(),/Сумма не определена/);await page.setViewportSize({width:390,height:844});assert(await root.locator('.billing-settlements__scroll').evaluate(e=>e.scrollWidth>e.clientWidth));await root.getByRole('button',{name:'Открыть начисления клиента'}).click();await root.getByRole('tab',{name:'Начисления',exact:true}).waitFor();assert.equal(await root.locator('.billing-settlements').count(),0);assert(calls.some(c=>c.url.includes('/billing/settlements')&&c.auth==='Bearer fixture'));assert(calls.every(c=>c.method==='GET'));assert.deepEqual(errors,[]);console.log('PASS actual production graph: tab, report, drilldown, unknown amount, mobile scroll, original review navigation, one React runtime');}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1});
