// TEST: actual Soul appearance and operational CSS, no production API requests.
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{createRequire}=require('node:module');
const web=path.resolve(__dirname,'../apps/web'),rw=createRequire(path.join(web,'package.json')),rv=createRequire(rw.resolve('vite/package.json'));
test('Winx is personal and Soul request rows are compact without clipping controls',async()=>{
 const code=`import React,{useState}from'react';import{createRoot}from'react-dom/client';import{SoulAppearance}from'./src/components/layout/SoulAppearance';function App(){const[user,U]=useState('8e175b30-8535-4881-9324-a875c9fd8c1d');return <><button id="other" onClick={()=>U('other')}>other</button><SoulAppearance key={user} userId={user}/></>};createRoot(document.getElementById('root')).render(<App/>);`;
 const built=await rv('esbuild').build({stdin:{contents:code,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'transform'});
 const {chromium}=require(process.env.WMS_TEST_PLAYWRIGHT),browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const width of [1440,1024,390]){
  const page=await browser.newPage({viewport:{width,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
  const request=`<td class="client-request-table__request-cell"><span class="client-request-number"><span class="client-request-number__prefix">№00</span><strong class="client-request-number__accent">1529</strong></span><strong class="client-request-title">FBS — 1 заказ</strong><span class="client-request-list-meta">Отгрузка · Обычный</span><span class="client-request-city"><span>Склад</span><strong>Маркетплейс FBS · Мой склад Москва Вешки</strong></span><span class="client-request-wb-supplies"><span>Поставка WB</span><strong>WB-GI-284953828</strong></span><span class="client-request-list-meta">Создана: 28.09.2026, 18:07</span><span class="client-request-list-meta">Автор: WMS</span><button class="client-request-row-fbs-link">К заказам FBS</button><button class="client-request-row-fbs-link">Маршрут</button></td>`;
  const row=`<tr>${request}<td class="client-request-table__client-cell"><strong>CL-000001</strong><span>ИП Лукин Илья Ильич</span></td><td class="client-request-table__composition-cell"><span class="client-request-items-count">1 позиций · 1 шт.</span><span class="client-request-fbs-completion">Собрано 0 из 1 · 0%</span><span class="client-request-items-preview">Костюм спортивный красный / XL × 1</span><button class="document-open-button">Состав XLSX</button></td><td class="client-request-table__warehouse-cell"><div class="client-request-actions client-request-actions--main">${['Остатки FBS','Инструкция','В ТСД','Собрать','Свой файл','Короба'].map(t=>'<button class="client-request-action-button">'+t+'</button>').join('')}</div></td><td class="client-request-table__process-cell"><select><option>Новая</option></select></td></tr>`;
  await page.route('http://winx.test/**',r=>r.fulfill({contentType:'text/html; charset=utf-8',body:`<html data-ui-variant="soul"><head><meta charset="utf-8"></head><body><div id="root"></div><div class="app-layout" data-ui-theme="modern"><section class="workspace-content"><div class="soul-workspace"><div class="soul-toolbar">title</div><div class="soul-page"><div class="client-request-table-wrap"><table class="data-table client-request-table"><tbody>${row}${row}</tbody></table></div></div></div></section></div></body></html>`}));
  await page.goto('http://winx.test');for(const file of ['src/styles.css','src/components/client-requests/client-requests.css','src/components/layout/soul-theme.css'])await page.addStyleTag({content:fs.readFileSync(path.join(web,file),'utf8')});
  await page.addScriptTag({content:built.outputFiles[0].text});await page.waitForFunction(()=>document.documentElement.dataset.soulMode==='winx');
  assert.ok(await page.locator('html').evaluate(el=>el.style.getPropertyValue('--soul-background').includes('soul-winx-20260929.png')));
  assert.equal(await page.locator('.soul-toolbar').evaluate(el=>getComputedStyle(el).borderColor),'rgb(201, 166, 221)');
  if(width===1440){assert.equal(await page.locator('.client-request-number__accent').first().evaluate(el=>getComputedStyle(el).fontSize),'20px');const measured=await page.locator('tbody tr').first().evaluate(el=>({height:el.getBoundingClientRect().height,cells:Array.from(el.children).map(c=>({class:c.className,height:c.getBoundingClientRect().height,width:c.getBoundingClientRect().width,children:Array.from(c.children).map(e=>({class:e.className,h:e.getBoundingClientRect().height,w:e.getBoundingClientRect().width,font:getComputedStyle(e).font,spacing:getComputedStyle(e).letterSpacing,children:Array.from(e.children).map(a=>({font:getComputedStyle(a).font,text:a.textContent}))}))}))}));assert.ok(measured.height<280,JSON.stringify(measured));}
  for(const button of await page.locator('tbody tr').first().locator('button').all()){const b=await button.boundingBox();assert.ok(b&&b.height>=28);assert.ok(await button.evaluate(el=>el.scrollHeight<=el.clientHeight+2),'no clipped button');}
  const rows=await page.locator('tbody tr').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{top:r.top,bottom:r.bottom}}));assert.ok(rows[1].top>=rows[0].bottom-1);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await page.locator('#other').click();await page.waitForFunction(()=>document.documentElement.dataset.soulMode==='light');
  assert.equal(await page.locator('option[value="winx"]').count(),0);assert.equal(await page.locator('.soul-toolbar').evaluate(el=>getComputedStyle(el).borderColor),'rgb(199, 203, 191)');assert.deepEqual(errors,[]);await page.close();
 }}finally{await browser.close();}
});
