// TEST: local visual fixture only. No session, API calls or production data.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),{createRequire}=require('node:module');
const web=path.resolve(__dirname,'../apps/web'),rw=createRequire(path.join(web,'package.json')),rv=createRequire(rw.resolve('vite/package.json'));
async function main(){
const result=await rv('esbuild').build({stdin:{contents:`
import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{SpiritChart}from'./src/components/analytics/SpiritChart';
function Preview(){const[period,setPeriod]=useState('7');const[selected,setSelected]=useState('');const rows=[{name:'Тестовый товар A',value:period==='7'?12450:25900},{name:'Тестовый товар B',value:7800},{name:'Тестовый возврат',value:-1200}];return <div className="app-layout" data-ui-theme="modern" data-ui-variant="spirit" style={{display:'block',height:'auto',minHeight:'100vh'}}><main className="workspace-shell" style={{gridTemplateRows:'minmax(0,1fr)'}}><div className="workspace-content"><div className="modern-dashboard"><header className="modern-dashboard__heading"><h1>Spirit · тестовые данные</h1></header><section className="modern-dashboard__metrics">{['Заказы','Филиалы','Отклонения','Выручка'].map((label,i)=><article key={label}><div><span>{label}</span><strong>{[126,2,3,'28 400 ₽'][i]}</strong><small>Тестовый показатель</small></div></article>)}</section><div className="analytics-panel"><section className="analytics-card"><div className="analytics-card__heading"><strong>Лидеры по заказам</strong><label>Период <select aria-label="Период" value={period} onChange={e=>setPeriod(e.target.value)}><option value="7">7 дней</option><option value="30">30 дней</option></select></label></div><SpiritChart rows={rows} onSelect={i=>setSelected(rows[i].name)}/><div className="analytics-bars">{rows.map((r,i)=><button key={r.name} onClick={()=>setSelected(r.name)}><span>{i+1}</span><span className="analytics-bars__label"><strong>{r.name}</strong></span><em>{r.value}</em></button>)}</div><p role="status">{selected}</p></section><section className="analytics-card analytics-products"><h2>Товары</h2><div className="analytics-table-wrap"><table className="analytics-table"><thead><tr>{['Товар','Статус','Заказы','Сумма','Конверсия','Выкуп','WB','LOGOFF','Динамика'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.name}><td><div className="analytics-product-identity"><strong>{r.name}</strong></div></td><td>Доступен</td><td>12</td><td>{r.value}</td><td>25%</td><td>92%</td><td>14</td><td>40</td><td><span className="analytics-dynamic positive">+12%</span></td></tr>)}</tbody></table></div></section></div></div></div></main></div>};createRoot(document.getElementById('root')).render(<Preview/>);`,resolveDir:web,loader:'tsx'},bundle:true,write:false,format:'iife',minify:false,target:'es2020'});
const js=result.outputFiles[0].text;
const routes={'/requests.css':path.join(web,'src/components/client-requests/client-requests.css'),'/styles.css':path.join(web,'src/styles.css'),'/analytics.css':path.join(web,'src/components/analytics/analytics.css'),'/spirit.css':path.join(web,'src/components/layout/spirit-theme.css')};
http.createServer((req,res)=>{const url=req.url.split('?')[0];if(url==='/preview.js'){res.setHeader('Content-Type','application/javascript');res.end(js);return}if(routes[url]){res.setHeader('Content-Type','text/css');res.end(fs.readFileSync(routes[url]));return}res.setHeader('Content-Type','text/html');res.end(url==='/requests'?fs.readFileSync(path.join(__dirname,'spirit-requests-preview.html'),'utf8'):url==='/frame'?`<!doctype html><html data-ui-theme="modern" data-ui-variant="spirit"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/analytics.css"><link rel="stylesheet" href="/spirit.css"><div id="root"></div><script src="/preview.js"></script></html>`:`<!doctype html><title>Spirit QA — local fixtures</title><style>body{margin:0;background:#0c1426;color:white;font:14px system-ui}button{padding:10px;margin:6px}iframe{display:block;border:0;height:1100px;background:#0c1426}</style><nav><button onclick="document.querySelector('iframe').style.width='1440px'">1440 desktop</button><button onclick="document.querySelector('iframe').style.width='768px'">768 tablet</button><button onclick="document.querySelector('iframe').style.width='375px'">375 mobile</button></nav><iframe title="Spirit preview" src="/frame" style="width:1440px"></iframe>`)}).listen(8770,'127.0.0.1',()=>console.log('Spirit fixture: http://127.0.0.1:8770'));
}
main().catch(e=>{console.error(e);process.exitCode=1});
