// TEST: compare original and candidate snapshots in one READ ONLY transaction; never apply the preference.
const {PrismaClient}=require('/app/apps/api/node_modules/@prisma/client');const p=new PrismaClient();const dist='/app/apps/api/dist/';
(async()=>{const {AuthService}=require(dist+'modules/auth/auth.service');const {WarehouseAuthScopeService}=require(dist+'modules/auth/warehouse-auth-scope.service');const {SystemSettingsService}=require(dist+'common/settings/system-settings.service');const {ClientScopeService}=require(dist+'modules/auth/client-scope.service');const {FboTwoStageService}=require(dist+'modules/tsd/fbo-two-stage.service');
const auth=new AuthService(p,null,null,null,null,null,new SystemSettingsService(p),null,new WarehouseAuthScopeService(p));const record=await p.user.findUnique({where:{id:'b045e060-dfd7-48af-bb88-12c191ee8eae'},include:auth.userAccessInclude()});if(record?.status!=='ACTIVE'||record.name!=='La_panthera')throw Error('Actor');const user=await auth.toAuthUser(record);const id='1c6568d2-5de8-4d66-8713-487157aeed7f';
const assert=require('node:assert/strict'),{createHash}=require('node:crypto');
const Module=require('module'),fs=require('fs');const base=new Module('/app/apps/api/dist/modules/tsd/fbo-two-stage.baseline.js');base.filename=base.id;base.paths=Module._nodeModulePaths('/app/apps/api/dist/modules/tsd');base._compile(fs.readFileSync('/proof/runtime.js','utf8'),base.filename);const old=new base.exports.FboTwoStageService(p,new ClientScopeService());const next=new FboTwoStageService(p,new ClientScopeService());
const hash=r=>createHash('sha256').update(JSON.stringify(r.items.map(i=>[i.id,i.skuId,i.barcode,i.quantity]).sort((a,b)=>String(a[0]).localeCompare(String(b[0]))))).digest('hex');
const result=await p.$transaction(async tx=>{
await tx.$executeRawUnsafe('SET TRANSACTION READ ONLY');const request=await old.load(tx,id,user,'read');assert.equal(request.number,1550);assert.equal(request.items.reduce((s,i)=>s+i.quantity,0),1833);old.requireFbo(request);
const receipts=await tx.stockMovement.findMany({where:{clientId:request.clientId,warehouseId:request.warehouseId,type:'RECEIPT',createdAt:{gte:new Date('2026-09-24')},box:{code:{startsWith:'FFL_LKB2409_'}}},select:{boxId:true},distinct:['boxId']});
const value={version:1,id,clientId:request.clientId,warehouseId:request.warehouseId,compositionHash:hash(request),preferredBoxIds:receipts.map(x=>x.boxId).filter(Boolean)};assert(value.preferredBoxIds.length);
const oldPlan=await old.snapshot(tx,request);const noPreference=await next.snapshot(tx,request);assert.deepEqual(noPreference.route,oldPlan.route,'default routing regression');
const proxy=new Proxy(tx,{get(t,k){if(k==='systemSetting')return{findUnique:async({where})=>where.key==='fbo.route.'+id?{value}:t.systemSetting.findUnique({where})};return t[k];}});
const plan=await next.snapshot(proxy,request);assert.deepEqual(plan.pickedUnits,oldPlan.pickedUnits);assert.deepEqual(plan.boxes,oldPlan.boxes);assert.deepEqual(plan.lines,oldPlan.lines);assert.equal(plan.shortage,oldPlan.shortage);
const sum=p=>({picked:p.picked,packed:p.packed,remaining:p.lines.reduce((s,l)=>s+l.remaining,0),boxes:p.route.length,whole:p.route.filter(b=>b.wholeBox).length,wholeQty:p.route.filter(b=>b.wholeBox).reduce((s,b)=>s+b.tasks.reduce((s,t)=>s+t.quantity,0),0),shortage:p.shortage});
const before=sum(oldPlan),after=sum(plan);assert(after.boxes<=before.boxes);assert(after.wholeQty>=before.wholeQty);assert.equal(plan.route.reduce((s,b)=>s+b.tasks.reduce((s,t)=>s+t.quantity,0),0)+plan.shortage,after.remaining);
return{passed:true,at:new Date(),before,after,value,plan};
},{isolationLevel:'RepeatableRead',timeout:30000});console.log(JSON.stringify(result));})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>p.$disconnect());
