// TEST: cancelled unfinished tasks require both cancellation and later physical-stock proof.
const {test}=require('node:test'),assert=require('node:assert/strict');
const {releaseCancelledBindings}=require('/app/apps/api/dist/common/kiz-cancelled-reuse');
const kiz='0104640569959645215PK)BydWsKINK';
function fixture(change={}){
 process.env.WMS_KIZ_CANCELLED_ADMIN_REUSE_ENABLED='true';process.env.WMS_KIZ_PHYSICAL_REVIEW_ENABLED='true';
 const task={id:'old',clientId:'c',requestId:'r',connectionId:'conn',orderId:'123',status:'RELEASED',completedAt:null,kiz,updatedAt:new Date('2026-09-13')};Object.assign(task,change.task);
 const proof={physicalTruth:true,quantity:1,targetClientId:'c',skuId:'s',markId:'m',targetBoxId:'b',targetWarehouseId:'w',movementId:'move'};const audits=[],updates=[];
 const tx={$queryRaw:async()=>[],fbsTsdAssembly:{findMany:async()=>[task],updateMany:async q=>{updates.push(q);return{count:1}}},clientRequest:{findMany:async()=>change.open?[]:[{id:'r'}]},fbsOrderRequestLink:{findFirst:async()=>change.notCancelled?null:{id:'link',lastSupplierStatus:'cancel',lastWbStatus:'canceled',handedOverAt:null}},shippedKizHistory:{findMany:async()=>change.shipped?[{kiz}]:[]},productMark:{findMany:async()=>[{id:'m',value:kiz,status:'AVAILABLE',boxId:'b',skuId:'s'}]},auditLog:{findFirst:async()=>change.noProof?null:{id:'proof',userId:'admin',createdAt:new Date('2026-09-23'),payload:proof},create:async q=>audits.push(q.data)},stockMovement:{findFirst:async()=>change.noMovement?null:{id:'move'}}};
 const evidence={decision:'REVIEW',checkedAt:new Date().toISOString(),circulation:null,orders:[{orderId:'123',verified:false}],...change.evidence};return{tx,evidence,audits,updates};
}
test('released never shipped task is archived only after confirmed cancellation and sorting',async()=>{const f=fixture();await releaseCancelledBindings(f.tx,'c',kiz,f.evidence,'admin','review','new',true);assert.equal(f.updates.length,1);assert.deepEqual(f.updates[0].data,{kiz:null});assert.equal(f.audits[0].action,'KIZ_UNFINISHED_CANCELLED_BINDING_ARCHIVED');assert.equal(f.audits[0].payload.before.id,'old');});
for(const [name,change,confirmed] of [['active',{task:{status:'IN_PROGRESS'}},true],['completed',{task:{completedAt:new Date()}},true],['open request',{open:true},true],['not cancelled',{notCancelled:true},true],['shipped',{shipped:true},true],['no sorting',{noProof:true},true],['no movement',{noMovement:true},true],['no physical confirmation',{},false],['retired',{evidence:{circulation:'RETIRED'}},true],['fresh active WB',{evidence:{orders:[{orderId:'123',verified:true,supplierStatus:'confirm',wbStatus:'waiting'}]}},true]])test('reject '+name,async()=>{const f=fixture(change);await assert.rejects(releaseCancelledBindings(f.tx,'c',kiz,f.evidence,'admin','review','new',confirmed));assert.equal(f.updates.length,0);});
