import 'reflect-metadata';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { receiptAllows, receiptOrderKey, receiptRules, receiptPublicationPolicy, receiptChannelChange, assertReceiptFbsBox, requireReceiptChannelAdmin, type ReceiptRule } from '../src/modules/warehouse/receipt-channel-policy';
import { FboFbsAvailability } from '../src/modules/tsd/fbo-fbs-reservations';
import { receiptStockSyncEvent } from '../src/modules/warehouse/receipt-channel-policy';
const old={marketplace:'WILDBERRIES',connectionId:'cabinet',orderId:'old'};
const rule:ReceiptRule={id:'r',clientId:'c',warehouseId:'w',sourceDocument:'SERIES:2026:FFL_TEST',fbs:false,fbo:true,protectedOrders:[receiptOrderKey(old)],revision:1,changedAt:new Date().toISOString()};
const task={...old,id:'t',requestId:'request',skuId:'sku',sourceSkuId:null,relabelConfirmedAt:null,boxId:null,reservedBoxId:null,itemCount:1};
const stock=[{boxId:'restricted',skuId:'sku',quantity:25},{boxId:'normal',skuId:'sku',quantity:2}];
function db(){return {box:{findMany:vi.fn(async()=>[{id:'restricted',code:'FFL_TEST_001',createdAt:new Date('2026-09-01')}])},systemSetting:{findMany:vi.fn(async()=>[{value:rule}]),findUnique:vi.fn(async()=>({value:rule})),upsert:vi.fn()},stockMovement:{findMany:vi.fn(async(args:any)=>args.where.status==='PACKING'?[]:args.select.sourceDocument?[{boxId:'restricted',sourceDocument:'SERIES:2026:FFL_TEST'}]:[{boxId:'restricted',createdAt:new Date('2026-09-01')}])},clientRequest:{findMany:vi.fn(async()=>[{id:'request'}])},fbsTsdAssembly:{findMany:vi.fn(async()=>[task])},stockBalance:{findMany:vi.fn(async()=>[{...stock[0]}])}} as any;}
beforeEach(()=>vi.stubEnv('WMS_RECEIPT_CHANNELS_ENABLED','true'));afterEach(()=>vi.unstubAllEnvs());
// TEST: both directions and membership saves await this durable invalidation.
it('invalidates old stock plans with a committed all-SKU event',async()=>{vi.stubEnv('WMS_WB_URGENT_STOCK_SYNC','true');const p={$executeRaw:vi.fn(async()=>1)};await receiptStockSyncEvent(p as any,'client');expect(p.$executeRaw).toHaveBeenCalledOnce();expect(p.$executeRaw.mock.calls[0][0].join('')).toContain('"WbStockSyncEvent"');expect(p.$executeRaw.mock.calls[0][1]).toBe('client');});
it('rolls back the caller if durable synchronization cannot be queued',async()=>{vi.stubEnv('WMS_WB_URGENT_STOCK_SYNC','true');await expect(receiptStockSyncEvent({$executeRaw:async()=>{throw Error('queue unavailable');}} as any,'client')).rejects.toThrow('queue unavailable');});
it('does not require the queue in a disabled installation',async()=>{vi.stubEnv('WMS_RECEIPT_CHANNELS_ENABLED','false');vi.stubEnv('WMS_WB_URGENT_STOCK_SYNC','true');const p={$executeRaw:vi.fn()};await receiptStockSyncEvent(p as any,'client');expect(p.$executeRaw).not.toHaveBeenCalled();});
// TEST: protected orders retain access; new demand cannot take FBO stock.
it('keeps old orders but rejects new orders and other accounts',()=>{expect(receiptAllows(rule,'fbs',old)).toBe(true);expect(receiptAllows(rule,'fbs',{...old,orderId:'new'})).toBe(false);expect(receiptAllows(rule,'fbs',{...old,connectionId:'other'})).toBe(false);expect(receiptAllows(rule,'fbo')).toBe(true);});
it('leaves sold WMS unchanged when disabled',async()=>{vi.stubEnv('WMS_RECEIPT_CHANNELS_ENABLED','false');const p=db();expect((await receiptRules(p,'c')).size).toBe(0);expect(p.systemSetting.findMany).not.toHaveBeenCalled();});
it('protects 1 old FBS unit and allows 24 for FBO',()=>{const a=new FboFbsAvailability(stock,[{...task,boxId:'restricted'}],new Map([['restricted',rule]]));expect(a.free('restricted','sku')).toBe(24);expect(()=>a.take('restricted','sku',25)).toThrow();a.take('restricted','sku',24);expect(a.free('restricted','sku')).toBe(0);});
it('new orders reserve only unrestricted stock',()=>{const a=new FboFbsAvailability(stock,[{...task,orderId:'new',itemCount:2}],new Map([['restricted',rule]]));expect(a.free('normal','sku')).toBe(0);expect(a.free('restricted','sku')).toBe(25);});
it('FBS-only receipt cannot be picked for FBO',()=>{const a=new FboFbsAvailability(stock,[],new Map([['restricted',{...rule,fbs:true,fbo:false}]]));expect(a.free('restricted','sku')).toBe(0);expect(a.free('normal','sku')).toBe(2);});
it('released demand does not republish restricted stock',async()=>{const p=db();p.fbsTsdAssembly.findMany.mockResolvedValue([]);const r=await receiptPublicationPolicy(p,'c','w');expect(r.blocked).toEqual(['restricted']);expect(r.credit.size).toBe(0);});
it('does not reserve ordinary stock twice',async()=>{expect((await receiptPublicationPolicy(db(),'c','w')).credit.get('sku')).toBe(1);});
it('does not credit a task assigned to another box',async()=>{const p=db();p.fbsTsdAssembly.findMany.mockResolvedValue([{...task,boxId:'normal'}]);expect((await receiptPublicationPolicy(p,'c','w')).credit.size).toBe(0);});
it('subtracts only unpicked units',async()=>{const p=db();p.fbsTsdAssembly.findMany.mockResolvedValue([{...task,itemCount:3}]);p.stockMovement.findMany.mockImplementation(async(a:any)=>a.where.status==='PACKING'?[{idempotencyKey:'fbs-sticker-pick:t:in',quantity:2}]:a.select.sourceDocument?[{boxId:'restricted',sourceDocument:'SERIES:2026:FFL_TEST'}]:[{boxId:'restricted',createdAt:new Date('2026-09-01')}]);expect((await receiptPublicationPolicy(p,'c','w')).credit.get('sku')).toBe(1);});
it('blocks stale route writes',async()=>{const p=db();await expect(assertReceiptFbsBox(p,{...old,clientId:'c',orderId:'new'},'restricted')).rejects.toThrow('только для ФБО');await expect(assertReceiptFbsBox(p,{...old,clientId:'c'},'restricted')).resolves.toBeUndefined();});
it('does not apply a prior year series to a reused box',async()=>{const p=db();p.stockMovement.findMany.mockResolvedValue([{boxId:'restricted',createdAt:new Date('2027-09-01')}]);expect((await receiptRules(p,'c','w')).size).toBe(0);});
it('checks branch and role',()=>{expect(()=>requireReceiptChannelAdmin({roleCodes:['ADMIN'],activeWarehouseId:'other',writableWarehouseIds:['w']})).toThrow();expect(()=>requireReceiptChannelAdmin({roleCodes:['PICKER'],activeWarehouseId:'w'})).toThrow();});
it('rejects both channels off before writing',async()=>{const p=db();await expect(receiptChannelChange(p,'c','w','r',false,false,1,true,'u')).rejects.toThrow('хотя бы одно');expect(p.systemSetting.upsert).not.toHaveBeenCalled();});
// TEST: a same-named receipt in another branch cannot override manual membership.
it('keeps manual membership within its branch',async()=>{const p=db();p.systemSetting.findMany.mockImplementation(async(a:any)=>a.where.key.startsWith.startsWith('receipt.membership')?[{value:{clientId:'c',warehouseId:'other',boxId:'manual',series:rule.sourceDocument}}]:[{value:rule},{value:{...rule,id:'other',warehouseId:'other',fbs:true}}]);p.box.findMany.mockResolvedValue([]);expect((await receiptRules(p,'c')).get('manual')?.warehouseId).toBe('other');expect((await receiptRules(p,'c')).get('manual')?.fbs).toBe(true);});
// TEST: future boxes of the same receipt inherit its saved direction before placement.
it('applies direction to a newly received box in the same series',async()=>{const p=db();p.box.findMany.mockResolvedValue([{id:'future',code:'FFL_TEST_999'}]);p.stockMovement.findMany.mockResolvedValue([{boxId:'future',createdAt:new Date('2026-09-30')}]);expect((await receiptRules(p,'c','w')).get('future')?.fbs).toBe(false);});
// TEST: allocation consumes a physical unit once, prioritizing the already assigned order.
it('credits only physical stock and prioritizes bound orders',async()=>{const p=db();p.stockBalance.findMany.mockResolvedValue([{boxId:'restricted',skuId:'sku',quantity:1}]);p.fbsTsdAssembly.findMany.mockResolvedValue([task,{...task,id:'bound',boxId:'restricted'}]);expect((await receiptPublicationPolicy(p,'c','w')).credit.get('sku')).toBe(1);});
