const fs=require('fs'),http=require('http'),assert=require('assert');const root=(process.env.WMS_DISPLAY_RELEASE_DIR||__dirname)+'/web';
const {chromium}=require('C:/Users/La_pa/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const exportsByChunk={0:'export{__pdSettings as TestSettings,iT as TestDom,x as TestReact,e as TestJsx};',6:'export{Ii as TestProgress,Bi as TestFbo};'};
(async()=>{const saved={},errors=[];const server=http.createServer((req,res)=>{
 if(req.url==='/fixture'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<div id="root"></div><div id="test"></div><script type="module">import{TestSettings,TestDom,TestReact as React,TestJsx as j}from"/assets/client-display-20260928-0.js";import{TestProgress}from"/assets/client-display-20260928-6.js";window.showProgress=()=>root.render(j.jsx(TestProgress,{plan:{needed:1,picked:0,packed:0,lines:[{id:"p",name:"HIDDEN NAME",article:"HIDDEN ARTICLE",size:"HIDDEN SIZE",barcode:"HIDDEN BARCODE",productDisplayText:"Visible M blue",needed:1,picked:0,packed:0,remaining:1}],route:[],pickedUnits:[]}}));const root=TestDom.createRoot(document.getElementById("test"));function App(){const[id,setId]=React.useState("one");return j.jsxs("div",{children:[j.jsx("button",{onClick:()=>setId("two"),children:"Другой клиент"}),j.jsx(TestSettings,{accessToken:"test",clientId:id},id)]})}root.render(j.jsx(App,{}));</script>');}
 if(req.url.includes('/api/v1/clients/')){const id=req.url.split('/')[4];res.setHeader('Content-Type','application/json');if(req.method==='PUT'){let raw='';req.on('data',v=>raw+=v);req.on('end',()=>{saved[id]=JSON.parse(raw).fields;res.end(JSON.stringify({clientId:id,fields:saved[id]}))});return;}return res.end(JSON.stringify({clientId:id,fields:saved[id]??null}));}
 const path=root+decodeURIComponent(req.url.split('?')[0]);if(!path.startsWith(root+'/assets/')||!fs.existsSync(path)){res.statusCode=404;return res.end()}
 res.setHeader('Content-Type',path.endsWith('.js')?'application/javascript':'text/css');let data=fs.readFileSync(path);const chunk=path.match(/client-display-20260928-(\d+)\.js$/);if(chunk&&exportsByChunk[chunk[1]])data=Buffer.concat([data,Buffer.from('\n'+exportsByChunk[chunk[1]])]);res.end(data);
 });await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port+'/fixture');await page.getByText('Отображение товара при сборке и упаковке',{exact:true}).click();await page.getByLabel('Использовать прежнее отображение').uncheck();await page.getByLabel('Наименование',{exact:true}).uncheck();await page.getByLabel('Цвет',{exact:true}).uncheck();await page.getByRole('button',{name:'Сохранить отображение',exact:true}).click();await page.getByRole('status').waitFor();assert.deepEqual(saved.one,['article','barcode','size']);await page.getByRole('button',{name:'Другой клиент'}).click();await page.getByText('Отображение товара при сборке и упаковке',{exact:true}).click();assert(await page.getByLabel('Использовать прежнее отображение').isChecked());await page.evaluate(()=>window.showProgress());await page.getByText('Visible M blue',{exact:true}).waitFor();assert(!(await page.locator('#test').innerText()).includes('HIDDEN'));assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/browser-proof.json',JSON.stringify({passed:true,saved,errors,productionGraph:true,fboFields:true}));console.log('PASS live graph: settings, save, client isolation, FBO hidden fields, no React errors');}finally{if(browser)await browser.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
